version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: merch-shop
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET_KEY=your_secure_jwt_secret_key_here
    depends_on:
      - db
      - redis
    networks:
      - internal

  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shop
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - internal

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - internal

networks:
  internal:
